### ISSUE TITLE
filter does not work in Lua 5.1

### ISSUE THREAD

**Issue by amir-sabbaghi** [jmespath/jmespath.lua#4]
A simple code such as this
```lua
j=require('cjson')
jp=require('jmespath')
print(j.encode(jp.search('[?A=="a"]', j.decode('[{"A": "a"}]'))))
```
does not work in Lua 5.1

**Comment by amir-sabbaghi** [comment]
I just found out that I should enclose literals with ` instead of double quotes. Why is there such a difference between the specification and implementation?

**Comment by mtdowling** [comment]
Literals in JMESPath support both backticks and single quotes, not double quotes.
